const todos = [
  {
    id: 'todo-satu',
    name: 'Read a book',
    highPriority: false,
    priority: true,
    finished: false,
    ownerId: 'users-1',
  },
  {
    id: 'todo-dua',
    name: 'Learn the course',
    highPriority: true,
    priority: false,
    finished: false,
    ownerId: 'users-2',
  },
  {
    id: 'todo-tiga',
    name: 'Complete project report',
    highPriority: true,
    priority: true,
    finished: false,
    ownerId: 'users-2',
  },
  {
    id: 'todo-empat',
    name: 'Exercise for 30 minutes',
    highPriority: false,
    priority: true,
    finished: false,
    ownerId: 'users-2',
  },
  {
    id: 'todo-lima',
    name: 'Prepare presentation',
    highPriority: true,
    priority: true,
    finished: false,
    ownerId: 'users-2',
  },
  {
    id: 'todo-enam',
    name: 'Grocery shopping',
    highPriority: false,
    priority: false,
    finished: false,
    ownerId: 'users-2',
  },
  {
    id: 'todo-tujuh',
    name: 'Visit the dentist',
    highPriority: true,
    priority: false,
    finished: false,
    ownerId: 'users-2',
  },
  {
    id: 'todo-delapan',
    name: 'Clean the house',
    highPriority: false,
    priority: true,
    finished: false,
    ownerId: 'users-2',
  },
  {
    id: 'todo-sembilan',
    name: 'Write a blog post',
    highPriority: true,
    priority: false,
    finished: false,
    ownerId: 'users-2',
  },
  {
    id: 'todo-sepuluh',
    name: 'Attend team meeting',
    highPriority: false,
    priority: true,
    finished: false,
    ownerId: 'users-2',
  },
  {
    id: 'todo-sebelas',
    name: 'Plan weekend trip',
    highPriority: true,
    priority: true,
    finished: false,
    ownerId: 'users-2',
  },
  {
    id: 'todo-duabelas',
    name: 'Study for exams',
    highPriority: true,
    priority: false,
    finished: false,
    ownerId: 'users-2',
  },
  {
    id: 'todo-tigabelas',
    name: 'Cook dinner',
    highPriority: false,
    priority: true,
    finished: false,
    ownerId: 'users-2',
  },
  {
    id: 'todo-empatbelas',
    name: 'Pay bills',
    highPriority: true,
    priority: true,
    finished: false,
    ownerId: 'users-2',
  },
  {
    id: 'todo-limabelas',
    name: 'Walk the dog',
    highPriority: false,
    priority: false,
    finished: false,
    ownerId: 'users-2',
  },
  {
    id: 'todo-enambelas',
    name: 'Call family',
    highPriority: true,
    priority: true,
    finished: false,
    ownerId: 'users-2',
  },
  {
    id: 'todo-tujuhbelas',
    name: 'Watch a documentary',
    highPriority: false,
    priority: true,
    finished: false,
    ownerId: 'users-2',
  },
  {
    id: 'todo-delapanbelas',
    name: 'Research project topic',
    highPriority: true,
    priority: false,
    finished: false,
    ownerId: 'users-2',
  },
  {
    id: 'todo-sembilanbelas',
    name: 'Meditate for 10 minutes',
    highPriority: false,
    priority: true,
    finished: false,
    ownerId: 'users-2',
  },
  {
    id: 'todo-duapuluh',
    name: 'Organize desk',
    highPriority: true,
    priority: true,
    finished: false,
    ownerId: 'users-2',
  },
];

module.exports = todos;
