const notes = [
  {
    id: 'notes-1',
    title: 'Hello, Notes!',
    body: 'My new notes.',
    archived: false,
    createdAt: '2022-07-28T10:12:12.396Z',
    ownerId: 'users-1',
  },
  {
    id: 'notes-2',
    title: 'Panduan Pengembangan Diri',
    body: 'Vivamus vitae tortor nec libero lacinia scelerisque. Cras congue libero ut lorem egestas, ac ullamcorper velit laoreet. Suspendisse sagittis convallis tortor. Nam nec libero neque. Praesent nec lectus id ligula tincidunt feugiat. Aenean a ante nec velit vulputate hendrerit et vel orci. Duis vel mauris libero. Pellentesque vestibulum dui id massa consectetur, et vulputate sem feugiat.',
    archived: false,
    createdAt: '2022-07-29T12:15:12.396Z',
    ownerId: 'users-2',
  },
  {
    id: 'notes-3',
    title: 'Tips Menulis Konten Kreatif',
    body: 'Nam fermentum libero ut ex scelerisque, et cursus tortor porttitor. Ut fermentum, lectus a suscipit facilisis, nulla sem vestibulum ligula, non blandit odio odio ac purus. Mauris ultrices neque eget libero cursus, vel vehicula ligula convallis. Vivamus vehicula tristique diam, a dignissim erat viverra at. Sed tempus dui eget fermentum tempor. Quisque ut diam libero. Suspendisse potenti. Fusce vitae nulla lacus.',
    archived: false,
    createdAt: '2022-07-30T14:20:12.396Z',
    ownerId: 'users-2',
  },
  {
    id: 'notes-4',
    title: 'Teknik Produktivitas Tinggi',
    body: 'Etiam auctor sem at lectus condimentum, in vehicula velit venenatis. Donec auctor diam at venenatis egestas. Praesent vel risus nisi. Aliquam suscipit velit vitae ligula finibus cursus. Integer dictum justo vitae arcu gravida, eget iaculis velit elementum. Vestibulum volutpat, odio a pretium scelerisque, felis dolor luctus mi, a auctor odio magna eu mauris.',
    archived: false,
    createdAt: '2022-07-31T16:25:12.396Z',
    ownerId: 'users-2',
  },
  {
    id: 'notes-5',
    title: 'Manajemen Waktu Efektif',
    body: 'Sed sit amet leo sit amet urna dignissim viverra. Cras euismod elit id tortor ullamcorper, id sodales risus aliquam. Phasellus blandit lorem ut varius interdum. Nunc vel purus eros. In ac dignissim augue. Aliquam vel feugiat nisi. Ut interdum lectus ut ultricies vehicula. Suspendisse venenatis fringilla neque nec blandit.',
    archived: false,
    createdAt: '2022-08-01T18:30:12.396Z',
    ownerId: 'users-2',
  },
  {
    id: 'notes-6',
    title: 'Cara Efektif Mengelola Tim',
    body: 'Integer ac posuere purus, ac congue dolor. Curabitur convallis libero et sollicitudin malesuada. Duis scelerisque diam sed bibendum mollis. Donec ultricies convallis nisi, nec vehicula dolor posuere eu. Nam dignissim diam non urna vehicula, in vehicula lorem sollicitudin. Sed varius tortor nec est aliquam, a iaculis sapien tempus.',
    archived: false,
    createdAt: '2022-08-02T20:35:12.396Z',
    ownerId: 'users-2',
  },
  {
    id: 'notes-7',
    title: 'Strategi Pemasaran Digital',
    body: 'Proin vehicula, quam a fermentum luctus, nisl augue fringilla lacus, sed ullamcorper lacus nisi in ipsum. Suspendisse potenti. Phasellus tristique vestibulum vestibulum. Vivamus vehicula, nisi et cursus cursus, elit ex porttitor dolor, at feugiat leo eros eget leo. Nullam gravida volutpat odio id sagittis. Mauris ut viverra ex.',
    archived: false,
    createdAt: '2022-08-03T22:40:12.396Z',
    ownerId: 'users-2',
  },
  {
    id: 'notes-8',
    title: 'Rencana Bisnis Startup',
    body: 'Nulla facilisi. In vitae mauris a tortor scelerisque convallis. Aliquam erat volutpat. Suspendisse vehicula, orci nec facilisis facilisis, mi nulla suscipit metus, id tristique nulla libero id felis. Proin vel facilisis metus, sit amet consectetur mi. Morbi faucibus dictum nisi a eleifend. Donec id sem id ex cursus suscipit.',
    archived: false,
    createdAt: '2022-08-04T10:45:12.396Z',
    ownerId: 'users-2',
  },
  {
    id: 'notes-9',
    title: 'Meningkatkan Kemampuan Komunikasi',
    body: 'Donec convallis orci non liberos dapibus, ac aliquet mauris lacinia. Nullam ullamcorper nisl et est faucibus, non scelerisque lorem blandit. Fusce in ex sed ligula suscipit gravida et ut odio. Integer non ipsum libero. In hac habitasse platea dictumst. Nullam sollicitudin augue a egestas gravida. Phasellus elementum turpis eget lectus dignissim, ut condimentum felis pretium.',
    archived: false,
    createdAt: '2022-08-05T12:50:12.396Z',
    ownerId: 'users-2',
  },
];

module.exports = notes;
